config/routes.rb
Objective::Application.routes.draw do

  
  devise_for :author, :controllers => { :sessions => "author/sessions", :registrations => "author/registrations" }
  
  namespace :author do

    match '/' => 'index#index'
    
    match '/posts' => 'posts#index'
    match '/posts/new' => 'posts#new'
    match '/posts/create' => 'posts#create'
    match '/posts/update' => 'posts#update'
    match '/posts/:post_name' => 'posts#show', :as => "posts_show"
    
    resources :install
    
  end

  root :to => 'blog#index'

end

app/models/author.rb
class Author
  
  include Mongoid::Document
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""
  
  #Fields
  field :first_name, type: String
  field :last_name, type: String

  #Validation
  validates_presence_of :first_name, message: "Please enter your first name"
  validates_presence_of :last_name, message: "Please enter your last name"
  
  validates_presence_of :email, message: "Please enter a valid email"
  
  validates_presence_of :password, message: "Please enter a password"
  validates_presence_of :password_confirmation, message: "Please confirm your password"
  validates_confirmation_of :password, message: "Passwords must match"
  
  validates_presence_of :encrypted_password

  #Associations  
  belongs_to :blog
  
  #Accessors
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation, :remember_me
  
  #Callbacks
  after_create :associate_author
  
  private
  
  def associate_author
  
  	blog = Blog.first
  	blog.author = self
  	
  	blog.save!
  	
  end
  
end

app/models/blog.rb
class Blog

	include Mongoid::Document
	
	#Associations
	has_one :author, validate: true
	has_one :metablog, validate: true
	
	has_many :posts, validate: false
	
	#Accessors
	attr_accessible :metablog, :author

end

app/models/metablog.rb
class Metablog
	
	include Mongoid::Document
  
	#DB Fields
	field :blog_name, type: String
	field :blog_description, type: String
	field :blog_domain, type: String
	
	#Validation
	validates_presence_of :blog_name, message: "Please enter a blog name"
	
	validates_length_of :blog_description, maximum: 256, message: "Tagline cannot exceed 256 characters"
	
	validates_presence_of :blog_domain, message: "Please enter your blog's domain name"
	
	#Associations
	belongs_to :blog
	
	#Accessors
	attr_accessible :blog_name, :blog_description, :blog_domain
	
end

app/models/metadata.rb
class MetaData

	include Mongoid::Document
	
	#DB Fields
	
	field :blog_name, type: String
	field :blog_description, type: String
	field :blog_domain, type: String
	
	#Validation
	
	validates_presence_of :blog_name, message: "Please enter a blog name"
	
	validates_length_of :blog_description, maximum: 256, message: "Tagline cannot exceed 256 characters"
	
	validates_presence_of :blog_domain, message: "Please enter your blog's domain name"
	
	#Associations
	belongs_to :blog
	
end

app/models/post.rb
class Post

	include Mongoid::Document
	include Mongoid::Timestamps

	#Fields
	field :title, type: String
	field :content, type: String
	field :slug, type: String

	#Associations
	belongs_to :blog
	
	#Callbacks
	before_create :create_slug
	
	def create_slug
		self.slug = self.title.parameterize
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/author/index_controller.rb
class Author::IndexController < AuthorController

  def index
  
  end
   
end

app/controllers/author/install_controller.rb
class Author::InstallController < ApplicationController

  layout 'install'

  def index
  	@blog = Blog.new
  	@blog.metablog = Metablog.new
  end
  
  def new
  	
  end
  
  def create
  
    @blog = Blog.new()
    @blog.metablog = Metablog.new(params[:metablog])

    respond_to do | format |
      if @blog.metablog.save
      	@blog.save
        format.html { redirect_to new_author_registration_path }
      else
        format.html { render action: "index" }
      end
    end
  end
  
end

app/controllers/author/posts_controller.rb
class Author::PostsController < AuthorController
  
  def index
  
  	@posts = Post.where(:slug.ne => nil)
  	
  end
  
  def new
  	
  	@post = Post.new
  	
  end
  
  def create
  
  	@post = Post.create(params[:post])
  	
  	if @post.save
  		flash[:notice] = "Post %s created successfully" % @post.title
  		redirect_to author_posts_path
  	else 
  		render :action => new
  	end
  	
  end
  
  def show
  
    @post = Post.find_by(slug: params[:post_name])
  	
  end
  
  def update
  
  	post_data = params[:post]
  	@post = Post.find_by(slug: post_data[:slug])
  	
  	if @post.update_attributes(post_data)
  		flash[:notice] = "Post %s updated successfully" % @post.title
  		redirect_to author_posts_path
  	end
  	
  end
  
end

app/controllers/author/registrations_controller.rb
class Author::RegistrationsController < Devise::RegistrationsController

	layout 'registrations'

end

app/controllers/author/sessions_controller.rb
class Author::SessionsController < Devise::SessionsController

	layout 'sessions'

end

app/controllers/author_controller.rb
class AuthorController < ApplicationController

  layout 'author'
  
  before_filter :bootstrap_blog
  
  private
  
  def bootstrap_blog
  
  	@blog = Blog.first
  	
  	if @blog.nil?
	  redirect_to author_install_index_path
  	else 
  		if @blog.author.nil?
  			redirect_to new_author_registration_path
  		else
  			authenticate_author!
  		end
  	end
  	
  end
  
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

  def index
  
  	@posts = Post.all()
  	@author = Author.first()
  	@metablog = Metablog.first
  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author/index_helper.rb
module Author::IndexHelper
end

app/helpers/author/install_helper.rb
module Author::InstallHelper
end

app/helpers/author/posts_helper.rb
module Author::PostsHelper
end

app/helpers/author/session_helper.rb
module Author::SessionHelper
end

app/helpers/author/sessions_helper.rb
module Author::SessionsHelper
end

app/helpers/author_helper.rb
module AuthorHelper

	def nav_link(link_text, link_path)
	  class_name = current_page?(link_path) ? 'active' : ''
	
	  content_tag(:li, :class => class_name) do
	    link_to link_text, link_path
	  end
	end
	
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/author/index/index.html.erb
<div class="row">
	<div class="span12" style="text-align:center;">
		<h1>Welcome</h1>
		<p class="lead">Welcome to Objective, a modern blogging/CMS system built with Ruby on Rails!</p>
		<hr />	
	</div>
</div>
<div class="row">
	<div class="span4">
		<h2 style="text-align:center">Objective.io Status</h2>
		<p class="text-success" style="text-align:center">All systems are running normally!</p>
		<ul>			
			<li>Cloud: Operational</li>
			<li>Backup: Operational</li>
		</ul>
	</div>
	<div class="span4">
		<h2 style="text-align:center">News &amp; Updates</h2>
		<ul>			
			<li><a href="#">Objective now supports custom widgets! - Check out the Widget Library now.</a></li>
			<li><a href="#">Some link to this other service that we just made available.</a></li>
		</ul>
	</div>
	<div class="span4">
		<h2 style="text-align:center">Blog Statistics</h2>
		<p><strong>Visitors currently on site: </strong>17</p>
		<p><strong>Most Visited Post: </strong><a href="#">Binary Property Lists</a></p>
		<p><strong>Visitors this month: </strong>179</p>
		<p><strong>Visitors YTD: </strong>1239</p>
	</div>
</div>

app/views/author/install/index.html.erb
<div class="row">
    <div class="span12" style="text-align:center;">
        <h1>Welcome</h1>

        <p class="lead">Objective Blogging Platform</p>

        <p>Thank you for installing Objective. Just enter the information below and then sit back and relax.<br>
        You'll be blogging in no time.</p>
        <hr>
    </div>
</div>

<div class="row">
    <div class="span9 offset2">
    	<%= form_for [:author, @blog.metablog], :url => author_install_index_path, :html => { :class => "form-horizontal" } do |f| %>
            <p class="lead">Blog Information</p>

            <div class="control-group <%= "error" unless @blog.metablog.errors[:blog_name].empty? %>">
                <label class="control-label" for="blog_name">Blog Name:</label>

                <div class="controls">
                    <%= f.text_field :blog_name, :class => "span4", :placeholder => "Enter a name for your blog" %>
                    <%= ("<span class=\"help-inline\">%s</span>" % @blog.metablog.errors[:blog_name]).html_safe unless @blog.metablog.errors[:blog_name].empty? %>
                </div>
            </div>
            
            <div class="control-group <%= "error" unless @blog.metablog.errors[:blog_description].empty? %>">
                <label class="control-label" for="blog_description">Blog Tagline:</label>

                <div class="controls">
	                <%= f.text_field :blog_description, :class => "span4", :placeholder => "Every blog has a good tagline" %>
	                <%= ("<span class=\"help-inline\">%s</span>" % @blog.metablog.errors[:blog_description]).html_safe unless @blog.metablog.errors[:blog_description].empty? %>
                </div>
            </div>
            
            <div class="control-group <%= "error" unless @blog.metablog.errors[:blog_domain].empty? %>">
                <label class="control-label" for="blog_domain">Domain:</label>

                <div class="controls">
                    <%= f.text_field :blog_domain, :class => "span4", :placeholder => "http://objective.io" %>
                    <%= ("<span class=\"help-inline\">%s</span>" % @blog.metablog.errors[:blog_domain]).html_safe unless @blog.metablog.errors[:blog_domain].empty? %>
                </div>
            </div>

            <div class="span7" style="text-align:center; margin-top:30px;">
                <%= f.submit :class => "btn btn-large", :value => "Install" %>
            </div>
        <% end %>
    </div>
</div>

app/views/author/posts/index.html.erb
<div class="row">
	<div class="span12" style="text-align:center;">
		<h1>Posts</h1>
		<p class="lead">Edit your blog posts, create new posts, and manage everything here.</p>
		<hr />	
	</div>
</div>
<% if flash.count > 0 %>
	<div class="row">
		<div class="span8 offset2">
			<% flash.each do | key, value | %>
				<div class="alert alert-success">
					<button type="button" class="close" data-dismiss="alert">x</button>
					<%= value %>
				</div>
			<% end %>
		</div>
	</div>
<% end %>
<div class="row">
	<div class="span12">
		<p>
			Here is a list of all the posts your currently have published or in progress.
			<a href="<%= author_posts_new_path %>" class="btn pull-right">New Post</a>
		</p>
		
		<table class="table table-bordered table-hover table-striped" style="margin-top:40px;">
			<thead>
				<tr>
					<th>#</th>
					<th>Post</th>
					<th>Created</th>
					<th>Status</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				<% @posts.each do | post | %>
					<tr>
						<td>1</td>
						<td><a href="<%= author_posts_show_path(:post_name => post.slug) %>"><%= post.title %></a></td>
						<td>Oct 5, 2012 8:00pm</td>
						<td>Published</td>
						<td>
							<div class="btn-group">
							  <button class="btn">Edit</button>
							  <button class="btn">Archive</button>
							  <button class="btn">Delete</button>
							</div>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
		<a href="<%= author_posts_new_path %>" class="btn pull-right">New Post</a>
		<div class="clearfix"></div>
		<p class="muted" style="text-align:center;">
			<%= pluralize(@posts.count, "Post") %> Total
		</p>
		<hr />	
	</div>
</div>
<div class="row">
	<div class="span12">
		<h3>Quick Post</h3>
		<p>Need to get a thought out there? Write a quick post below and publish it.</p>
	</div>
</div>
<div id="quick-post" class="row">
	<div class="span8">
		<div class="controls">
			<textarea rows="10" class="span8 redactor" type="text"></textarea>
		</div>
	</div>
	<div class="span4">
		<div class="well well-small">
			<p>Published in: <a href="#">Uncategorized</a></p>
			<p>Published: Today at 8:12pm</p>
			<p>Tags:</p>
			<div class="tags" style="margin-bottom:10px;">
				<span class="label label-info">iOS</span>
				<span class="label label-info">Engineering</span>
				<span class="label label-info">iOS 6</span>
				<span class="label label-info">Apple</span>
				<span class="label label-info">Rant</span>
			</div>
			<hr />
			<input type="submit" id="create-quick-post" name="create-quick-post" value="Publish" class="btn btn-primary" />
			<input type="submit" id="create-quick-post" name="create-quick-post" value="Create Draft" class="btn" />
		</div>
	</div>
</div>

app/views/author/posts/new.html.erb
<div class="row">
	<div class="span12" style="text-align:center;">
		<h1>New Post</h1>
		<p class="lead">Create a new blog post below.</p>
		<hr />	
	</div>
</div>
<%= form_for([:author, @post], :url => author_posts_create_path, :html => { :class => "form-inline" } ) do |f| %>
<div class="row">
	<div class="span12">
		<div class="row">
			<div class="span12">
			    <label for="title" style="margin-right: 10px;"><h5>Title:</h5></label>
			    <%= f.text_field :title, :class => "span6", :placeholder => "Post Title" %>
			</div>			
		</div>
		<div class="row">
			<div class="span12">
			<%= f.submit :class => "btn btn-primary pull-right", :value => "Create" %>
			</div>
		</div>
		<hr />
	</div>
</div>
<div id="new-post" class="row">
	<div class="span12">
		<p class="pull-left">Last Save: Just Now</p>
		<p class="pull-right">Current Status: <strong>Draft</strong></p>
		<div class="clearfix"></div>
		<div class="navbar">
			<div class="navbar-inner">
				<form class="navbar-form">
				  <button type="button" class="btn">B</button>
				  <button type="button" class="btn">I</button>
				  <button type="button" class="btn">H1</button>
				  <button type="button" class="btn">H2</button>
				  <button type="button" class="btn">&lt;a&gt;</button>
				  <button type="button" class="btn">&lt;img&gt;</button>
				  <button type="button" class="btn">&lt;hr&gt;</button>
				</form>
			</div>
		</div>
		
		<%= f.text_area :content, :class => "span12", :rows => 12 %>
		
		<br />
		<hr />
		<div>
			<h3>More Information</h3>
			<p>Use the information in this section optionally to add meta-data into this blog post. Meta-data greatly improves SEO and will help more people find the content you are creating.</p>
			<div class="row">
				<div class="span4">
					<h5>Primary Category</h5>
					<select name="primary-category">
						<option value="1">iOS</option>
						<option value="2">OSX</option>
						<option value="2">Cocoa</option>
					</select>
					<h5 class="muted">Secondary Category</h5>
					<select name="primary-category">
						<option value="1">iOS</option>
						<option value="2">OSX</option>
						<option value="2">Cocoa</option>
					</select>
				</div>
				<div class="span4">
					<h5>Tags</h5>
					<span class="label label-info">iOS</span>
					<span class="label label-info">Engineering</span>
					<span class="label label-info">iOS 6</span>
					<span class="label label-info">Apple</span>
					<span class="label label-info">Rant</span>
					<span class="label label-info">iOS</span>
					<span class="label label-info">Engineering</span>
					<span class="label label-info">iOS 6</span>
					<span class="label label-info">Apple</span>
					<span class="label label-info">Rant</span>
					<span class="label label-info">iOS</span>
					<span class="label label-info">Engineering</span>
					<span class="label label-info">iOS 6</span>
					<span class="label label-info">Apple</span>
					<span class="label label-info">Rant</span>
					<span class="label label-info">iOS</span>
					<span class="label label-info">Engineering</span>
					<span class="label label-info">iOS 6</span>
					<span class="label label-info">Apple</span>
					<span class="label label-info">Rant</span>
					<span class="label label-info">iOS</span>
					<span class="label label-info">Engineering</span>
					<span class="label label-info">iOS 6</span>
					<span class="label label-info">Apple</span>
					<span class="label label-info">Rant</span>
				</div>
				<div class="span4">
					<h5>Meta Title:</h5>
					<input type="text" class="input-large" name="meta-title" id="meta-title" />
					<h5>Keywords:</h5>
					<textarea class="span4" rows="3" name="meta-keywords" id="meta-keywords"></textarea>
				</div>
			</div>
		</div>
		<hr />
		<%= f.submit :class => "btn btn-primary pull-right", :value => "Create" %>
	</div>
</div>
<% end %>

app/views/author/posts/show.html.erb
<div class="row">
	<div class="span12" style="text-align:center;">
		<h1>Update Post</h1>
		<p class="lead">Update your post here. Make it sing.</p>
		<hr />	
	</div>
</div>
<%= form_for([:author, @post], :url => author_posts_update_path, :html => { :class => "form-inline" } ) do |f| %>
<%= f.hidden_field :slug, { :value => @post.slug } %>
<div class="row">
	<div class="span12">
		<div class="row">
			<div class="span12">
			    <h3><%= @post.title %></h3>
			</div>			
		</div>
		<div class="row">
			<div class="span12">
			<%= f.submit :class => "btn btn-primary pull-right", :value => "Update" %>
			</div>
		</div>
		<hr />
	</div>
</div>
<div id="new-post" class="row">
	<div class="span12">
		<p class="pull-left">Last Save: Just Now</p>
		<p class="pull-right">Current Status: <strong>Draft</strong></p>
		<div class="clearfix"></div>
		<div class="navbar">
			<div class="navbar-inner">
				<form class="navbar-form">
				  <button type="button" class="btn">B</button>
				  <button type="button" class="btn">I</button>
				  <button type="button" class="btn">H1</button>
				  <button type="button" class="btn">H2</button>
				  <button type="button" class="btn">&lt;a&gt;</button>
				  <button type="button" class="btn">&lt;img&gt;</button>
				  <button type="button" class="btn">&lt;hr&gt;</button>
				</form>
			</div>
		</div>
		
		<%= f.text_area :content, :class => "span12", :rows => 12 %>
		
		<br />
		<hr />
		<div>
			<h3>More Information</h3>
			<p>Use the information in this section optionally to add meta-data into this blog post. Meta-data greatly improves SEO and will help more people find the content you are creating.</p>
			<div class="row">
				<div class="span4">
					<h5>Primary Category</h5>
					<select name="primary-category">
						<option value="1">iOS</option>
						<option value="2">OSX</option>
						<option value="2">Cocoa</option>
					</select>
					<h5 class="muted">Secondary Category</h5>
					<select name="primary-category">
						<option value="1">iOS</option>
						<option value="2">OSX</option>
						<option value="2">Cocoa</option>
					</select>
				</div>
				<div class="span4">
					<h5>Tags</h5>
					<span class="label label-info">iOS</span>
					<span class="label label-info">Engineering</span>
					<span class="label label-info">iOS 6</span>
					<span class="label label-info">Apple</span>
					<span class="label label-info">Rant</span>
					<span class="label label-info">iOS</span>
					<span class="label label-info">Engineering</span>
					<span class="label label-info">iOS 6</span>
					<span class="label label-info">Apple</span>
					<span class="label label-info">Rant</span>
					<span class="label label-info">iOS</span>
					<span class="label label-info">Engineering</span>
					<span class="label label-info">iOS 6</span>
					<span class="label label-info">Apple</span>
					<span class="label label-info">Rant</span>
					<span class="label label-info">iOS</span>
					<span class="label label-info">Engineering</span>
					<span class="label label-info">iOS 6</span>
					<span class="label label-info">Apple</span>
					<span class="label label-info">Rant</span>
					<span class="label label-info">iOS</span>
					<span class="label label-info">Engineering</span>
					<span class="label label-info">iOS 6</span>
					<span class="label label-info">Apple</span>
					<span class="label label-info">Rant</span>
				</div>
				<div class="span4">
					<h5>Meta Title:</h5>
					<input type="text" class="input-large" name="meta-title" id="meta-title" />
					<h5>Keywords:</h5>
					<textarea class="span4" rows="3" name="meta-keywords" id="meta-keywords"></textarea>
				</div>
			</div>
		</div>
		<hr />
		<%= f.submit :class => "btn btn-primary pull-right", :value => "Update" %>
	</div>
</div>
<% end %>

app/views/author/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/blog/_post.html.erb
<%  markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true) %>

<h1><%= post.title %></h1>

<%= markdown.render(post.content).html_safe %>

app/views/blog/_sidebar.html.erb
<div class="pagination-centered">
	<%= link_to(image_tag("ObjIO.png"), root_url) %>
</div>
<h1><%= metablog.blog_name %></h1>
<p class="lead"><%= metablog.blog_description %></p>
<p class="lead muted" style="margin-left:3px;"><%= author.first_name + " " + author.last_name %></p>

<hr />

<h5><a href="#">Who Am I?</a></h5>
<h5><a href="#">Get In Touch</a></h5>
<h5><a href="#">Feed</a></h5>

app/views/blog/index.html.erb
<div class="post" style="margin: 20px 0px 60px 0px; padding-bottom:20px; border-bottom:1px solid #EEE">

	<% @posts.each do | post | %>
		<%= render partial: "post", locals: {:post => post } %>
	<% end %>
	
</div>