config/routes.rb
Objective::Application.routes.draw do

  
  devise_for :author, :controllers => { :sessions => "author/sessions", :registrations => "author/registrations" }
  
  namespace :author do

    match '/' => 'index#index'
    
    match '/posts' => 'posts#index'
    match '/posts/new' => 'posts#new'
    match '/posts/create' => 'posts#create'
    match '/posts/update' => 'posts#update'
    match '/posts/:post_name' => 'posts#show', :as => "posts_show"
    
    resources :install
    
  end

  root :to => 'blog#index'

end

app/models/author.rb
class Author
  
  include Mongoid::Document
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""
  
  #Fields
  field :first_name, type: String
  field :last_name, type: String

  #Validation
  validates_presence_of :first_name, message: "Please enter your first name"
  validates_presence_of :last_name, message: "Please enter your last name"
  
  validates_presence_of :email, message: "Please enter a valid email"
  
  validates_presence_of :password, message: "Please enter a password"
  validates_presence_of :password_confirmation, message: "Please confirm your password"
  validates_confirmation_of :password, message: "Passwords must match"
  
  validates_presence_of :encrypted_password

  #Associations  
  belongs_to :blog
  
  #Accessors
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation, :remember_me
  
  #Callbacks
  after_create :associate_author
  
  private
  
  def associate_author
  
  	blog = Blog.first
  	blog.author = self
  	
  	blog.save!
  	
  end
  
end

app/models/blog.rb
class Blog

	include Mongoid::Document
	
	#Associations
	has_one :author, validate: true
	has_one :metablog, validate: true
	
	has_many :posts, validate: false
	
	#Accessors
	attr_accessible :metablog, :author

end

app/models/metablog.rb
class Metablog
	
	include Mongoid::Document
  
	#DB Fields
	field :blog_name, type: String
	field :blog_description, type: String
	field :blog_domain, type: String
	
	#Validation
	validates_presence_of :blog_name, message: "Please enter a blog name"
	
	validates_length_of :blog_description, maximum: 256, message: "Tagline cannot exceed 256 characters"
	
	validates_presence_of :blog_domain, message: "Please enter your blog's domain name"
	
	#Associations
	belongs_to :blog
	
	#Accessors
	attr_accessible :blog_name, :blog_description, :blog_domain
	
end

app/models/metadata.rb
class MetaData

	include Mongoid::Document
	
	#DB Fields
	
	field :blog_name, type: String
	field :blog_description, type: String
	field :blog_domain, type: String
	
	#Validation
	
	validates_presence_of :blog_name, message: "Please enter a blog name"
	
	validates_length_of :blog_description, maximum: 256, message: "Tagline cannot exceed 256 characters"
	
	validates_presence_of :blog_domain, message: "Please enter your blog's domain name"
	
	#Associations
	belongs_to :blog
	
end

app/models/post.rb
class Post

	include Mongoid::Document
	include Mongoid::Timestamps

	#Fields
	field :title, type: String
	field :content, type: String
	field :slug, type: String

	#Associations
	belongs_to :blog
	
	#Callbacks
	before_create :create_slug
	
	def create_slug
		self.slug = self.title.parameterize
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/author/index_controller.rb
class Author::IndexController < AuthorController

  def index
  
  end
   
end

app/controllers/author/install_controller.rb
class Author::InstallController < ApplicationController

  layout 'install'

  def index
  	@blog = Blog.new
  	@blog.metablog = Metablog.new
  end
  
  def new
  	
  end
  
  def create
  
    @blog = Blog.new()
    @blog.metablog = Metablog.new(params[:metablog])

    respond_to do | format |
      if @blog.metablog.save
      	@blog.save
        format.html { redirect_to new_author_registration_path }
      else
        format.html { render action: "index" }
      end
    end
  end
  
end

app/controllers/author/posts_controller.rb
class Author::PostsController < AuthorController
  
  def index
  
  	@posts = Post.where(:slug.ne => nil)
  	
  end
  
  def new
  	
  	@post = Post.new
  	
  end
  
  def create
  
  	@post = Post.create(params[:post])
  	
  	if @post.save
  		flash[:notice] = "Post %s created successfully" % @post.title
  		redirect_to author_posts_path
  	else 
  		render :action => new
  	end
  	
  end
  
  def show
  
    @post = Post.find_by(slug: params[:post_name])
  	
  end
  
  def update
  
  	post_data = params[:post]
  	@post = Post.find_by(slug: post_data[:slug])
  	
  	if @post.update_attributes(post_data)
  		flash[:notice] = "Post %s updated successfully" % @post.title
  		redirect_to author_posts_path
  	end
  	
  end
  
end

app/controllers/author/sessions_controller.rb
class Author::SessionsController < Devise::SessionsController

	layout 'sessions'

end

app/controllers/author_controller.rb
class AuthorController < ApplicationController

  layout 'author'
  
  before_filter :bootstrap_blog
  
  private
  
  def bootstrap_blog
  
  	@blog = Blog.first
  	
  	if @blog.nil?
	  redirect_to author_install_index_path
  	else 
  		if @blog.author.nil?
  			redirect_to new_author_registration_path
  		else
  			authenticate_author!
  		end
  	end
  	
  end
  
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

  def index
  
  	@posts = Post.all()
  	@author = Author.first()
  	@metablog = Metablog.first
  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author/index_helper.rb
module Author::IndexHelper
end

app/helpers/author/install_helper.rb
module Author::InstallHelper
end

app/helpers/author/posts_helper.rb
module Author::PostsHelper
end

app/helpers/author/session_helper.rb
module Author::SessionHelper
end

app/helpers/author/sessions_helper.rb
module Author::SessionsHelper
end

app/helpers/author_helper.rb
module AuthorHelper

	def nav_link(link_text, link_path)
	  class_name = current_page?(link_path) ? 'active' : ''
	
	  content_tag(:li, :class => class_name) do
	    link_to link_text, link_path
	  end
	end
	
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">

    <title>Objective</title>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= csrf_meta_tags %><!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    
    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
</head>

<body data-spy="scroll" data-target=".obj-sidebar">
    <div class="container-fluid">
    	<div class="content" style="padding:20px;">
	        <div class="row-fluid">
	            <div class="span3" style="border-top:5px solid #87b0da">
	            	<%= render :partial => "sidebar", :locals => { :metablog => @metablog, :author => @author }  %>
	            </div>
	
	            <div class="span8" style="border-top:5px solid #87b0da">
	                <%= yield %>
	            </div>
	        </div> <!--- /row --->
	        <hr>

		    <footer>
		        <p>&copy; Objective.io 2012</p>
		    </footer>
    	</div> <!--- content --->
    </div> <!--- /container --->
    
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
</body>
</html>

app/views/layouts/author.html.erb
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">

    <title>Objective</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <%= csrf_meta_tags %>
    
    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    
    <style type="text/css">
    	body {
		  position: relative;
		  padding-top: 40px;
		}
    </style>
    
    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
</head>

<body>

	<div class="navbar navbar-fixed-top">
		<!-- Navigation -->
        <div class="navbar-inner">
            <div class="container">
                
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"></button> 
                
                <span class="brand">Objective</span>

                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <%= nav_link 'Home', author_path %>

                        <%= nav_link 'Posts', author_posts_path %>

                        <li><a href="#">Pages</a></li>

                        <li><a href="#">Themes</a></li>

                        <li><a href="#">Navigation</a></li>

                        <li><a href="#">Settings</a></li>
                    </ul>
                    <ul class="nav pull-right"> 
                    	<li><%= link_to 'View Site', root_path, :target => "_blank" %></li>
                    	<li class="divider-vertical"></li>
                    	<li class="dropdown">
                    		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    			<i class="icon-user"></i><%= current_author.first_name %> <b class="caret"></b>
                    		</a> 
                    		<ul class="dropdown-menu">
	                    		<li><a href="#">Notifications</a></li>
	                    		<li><a href="#">My Account</a></li> 
	                    		<li class="divider"></li>
	                    		<li><%= link_to "Sign Out", destroy_author_session_path, :method => :delete %></li>
                    		</ul> 
                    	</li>
                    </ul>
                </div>
            </div>
        </div>
    </div> <!-- /navbar -->
    
    <!-- layout -->
    <div class="container">
    	<div class="author-content" style="margin-top:40px;">
	    	<%= yield %>
    	</div>
    	
    	<hr />
    	
    	<footer style="margin-bottom:40px;">
    		&copy; Objective.io 2012
    	</footer>
        
    </div><!--- /container =-->
    
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
</body>
</html>

app/views/layouts/install.html.erb
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">

    <title>Objective</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <%= csrf_meta_tags %>
    
    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    
    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
</head>

<body>
    
    <!-- layout -->
    <div class="container">
    	<div class="admin-content" style="margin-top:40px;">
	    	<%= yield %>
    	</div>
    	
    	<hr />
    	
    	<footer style="margin-bottom:40px;">
    		&copy; Objective.io 2012
    	</footer>
        
    </div><!--- /container =-->
    
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
</body>
</html>

app/views/layouts/registrations.html.erb
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">

    <title>Objective</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <%= csrf_meta_tags %>
    
    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    
    <style type="text/css">
    	body {
		  position: relative;
		  padding-top: 40px;
		}
    </style>
    
    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
</head>

<body>

	<div class="navbar navbar-fixed-top">
		<!-- Navigation -->
        <div class="navbar-inner">
            <div class="container">
                
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"></button> 
                
                <a class="brand" href="#">Objective</a>

            </div>
        </div>
    </div> <!-- /navbar -->
    
    <!-- layout -->
    <div class="container">
    	<div class="author-content" style="margin-top:40px;">
	    	<%= yield %>
    	</div>
    	
    	<hr />
    	
    	<footer style="margin-bottom:40px;">
    		&copy; Objective.io 2012
    	</footer>
        
    </div><!--- /container =-->
    
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
</body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">

    <title>Objective</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <%= csrf_meta_tags %>
    
    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    
    <style type="text/css">
    	body {
		  position: relative;
		  padding-top: 40px;
		}
    </style>
    
    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
</head>

<body>

	<div class="navbar navbar-fixed-top">
		<!-- Navigation -->
        <div class="navbar-inner">
            <div class="container">
                
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"></button> 
                
                <span class="brand">Objective</span>

                <div class="nav-collapse collapse">
                    <ul class="nav pull-right"> 
                    	<li><a href="<%= root_path %>">Back to Site</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div> <!-- /navbar -->
    
    <!-- layout -->
    <div class="container">
    	<div class="author-content" style="margin-top:40px;">
	    	<%= yield %>
    	</div>
    	
    	<hr />
    	
    	<footer style="margin-bottom:40px;">
    		&copy; Objective.io 2012
    	</footer>
        
    </div><!--- /container =-->
    
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
</body>
</html>